### ISSUE TITLE
[Feature Request] Hiding and Unhiding

### ISSUE THREAD

**Issue by EuanHoll** [IyesGames/iyes_perf_ui#12]
Hi,

First thanks for making this package, it is super useful.

I may be wrong, I'm new to Bevy, but there seems to be no easy way to hide and unhide the UI. 
I feel like this would be a useful feature as it will allow us to incorporate these into in-game settings.

**Comment by honungsburk** [comment]
I'm guessing that you can use Bevy' builtin components for visibility: https://bevy-cheatbook.github.io/fundamentals/visibility.html

 it will work

**Comment by honungsburk** [comment]
I've confirmed that it works. My code:

```rust

fn update_visibility(
    mut query: Query<&mut Visibility, With<PerfUiRoot>>,
    performance_ui_flag_op: Option<ResMut<ShowPerformanceUIFlag>>,
) {
    if let Some(performance_ui_flag) = performance_ui_flag_op {
        if performance_ui_flag.is_changed() {
            for mut viz in query.iter_mut() {
                *viz = if performance_ui_flag.is_on() {
                    Visibility::Inherited
                } else {
                    Visibility::Hidden
                };
            }
        }
    }
}

```

**Comment by EuanHoll** [comment]
Hi 

> ```rust
> if let Some(performance_ui_flag) = performance_ui_flag_op {
>         if performance_ui_flag.is_changed() {
>             for mut viz in query.iter_mut() {
>                 *viz = if performance_ui_flag.is_on() {
>                     Visibility::Inherited
>                 } else {
>                     Visibility::Hidden
>                 };
>             }
>         }
>     }
> ```

Thanks for looking into this. As I said I'm new to bevy so there are a fair few things I'm missing.

Quick question, is the ShowPErformanceUIFlag a flag you added yourself or something native to `iyes_perf_ui`?

**Comment by EuanHoll** [comment]
Cool. Then I think I can mark this closed. Thanks for the help!

**Comment by honungsburk** [comment]
Note that the system must be ordered after the `PerfUiSet:.Setup`

example:
` .add_systems(Update, update_visibility.after(PerfUiSet::Setup));`
